sudo: required
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
  - docker 
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # unencrypts the gcp service acc key
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download gcloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # apply gcloud config file
  - gcloud components update kubectl # install the kubectl
  - gcloud auth activate-service-account --key-file service-account.json # authentication for gcp
  - gcloud config set project multi-k8s-326309 # specify which project to connect to 
  - gcloud config set compute/zone us-central1-c # specify which zone to connect to 
  - gcloud container clusters get-credentials multi-cluster # specify which cluster to work with
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin # login to the docker cli
  - docker build -t tommydo89/react-test -f ./client/Dockerfile.dev ./client # ./client/Dockerfile.dev is the file  and ./client is the build context

script:
  - docker run -e CI=true tommydo89/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branches: master