sudo: required
services:
  - docker 
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # unencrypts the gcp service acc key
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download gcloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # apply gcloud config file
  - gcloud components update kubectl # install the kubectl
  - gcloud auth activate-service-account --key-file service-account.json # authentication for gcp
